<a href="https://colab.research.google.com/github/Akhilvijayanponmudy/pytorch/blob/main/creating_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
tensor_from_list = torch.tensor([1,2,3])

In [2]:
print(tensor_from_list)

tensor([1, 2, 3])


In [3]:
import numpy as np
numpy_array = np.array([[1,2,3],[4,5,6]])
tensor_from_numpy = torch.tensor(numpy_array)
print(tensor_from_numpy)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
#crating tensors with specific values

tensor_zeros = torch.zeros(3,3)
tensor_ones = torch.ones(2,2)
print(tensor_zeros)
print(tensor_ones)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [5]:
#Random Tensors

random_tensor = torch.rand(4,4)
normal_tensor = torch.randn(4,4)
print(random_tensor)
print(normal_tensor)

tensor([[0.9747, 0.7985, 0.9739, 0.8312],
        [0.2866, 0.7681, 0.8995, 0.5496],
        [0.5556, 0.2984, 0.1962, 0.2641],
        [0.7824, 0.3885, 0.1726, 0.1652]])
tensor([[-0.0781, -0.2852,  1.0412, -1.1473],
        [ 0.1825,  1.1878, -0.7150,  1.6304],
        [ 0.1787, -1.1809, -1.6999, -0.8321],
        [ 0.3259, -0.2865,  0.7934,  0.4104]])
