<a href="https://colab.research.google.com/github/Akhilvijayanponmudy/pytorch/blob/main/pytorch_learning_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch


In [ ]:
tensor_a =torch.rand(3,3)
tensor_b =torch.rand(3,3)

result = torch.matmul(tensor_a,tensor_b)

In [ ]:
print(tensor_a)
print("------------------------")

print(tensor_b)
print("------------------------")

print(result)


tensor([[0.2737, 0.1663, 0.3654],
        [0.7605, 0.4881, 0.3352],
        [0.5168, 0.7740, 0.8536]])
------------------------
tensor([[0.6641, 0.0666, 0.3115],
        [0.8826, 0.0263, 0.1433],
        [0.2201, 0.5848, 0.4555]])
------------------------
tensor([[0.4090, 0.2363, 0.2755],
        [1.0096, 0.2595, 0.4595],
        [1.2143, 0.5540, 0.6607]])


In [ ]:
if torch.cuda.is_available():
    torch_a=tensor_a.to('cuda')
    torch_b=tensor_b.to('cuda')
    result=torch.matmul(torch_a,torch_b)
    print(result)

else:
    print("Torch.cuda is not available")

tensor([[0.4090, 0.2363, 0.2755],
        [1.0096, 0.2595, 0.4595],
        [1.2143, 0.5540, 0.6607]], device='cuda:0')
